# automatically generated by the FlatBuffers compiler, do not modify

# namespace: inbox

import flatbuffers

class GetConversationsResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetConversationsResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetConversationsResponse()
        x.Init(buf, n + offset)
        return x

    # GetConversationsResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetConversationsResponse
    def Conversations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Conversation import Conversation
            obj = Conversation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GetConversationsResponse
    def ConversationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GetConversationsResponseStart(builder): builder.StartObject(1)
def GetConversationsResponseAddConversations(builder, conversations): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(conversations), 0)
def GetConversationsResponseStartConversationsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GetConversationsResponseEnd(builder): return builder.EndObject()
